# Generated by Django 3.0.10 on 2020-10-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikifisc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'verbose_name': 'Wiki page', 'verbose_name_plural': 'Wiki Pages'},
        ),
    ]
